import type { MediaItem } from '@/types/media'

export const MEDIA: MediaItem[] = [
  {
    id: 'featured-1',
    title: 'THE MAIN CHARACTER',
    type: 'image',
    thumbnail: 'Featured/slide1.jpg',
    mediaUrl: 'Featured/slide1.jpg',
    category: 'Featured',
    tags: ['featured', 'slide', 'first'],
    favorite: true,
    date: '2026-07-31',
    description: 'An absolute visual masterpiece. Highly recommended for infinite rewatches.',
  },
  {
    id: 'featured-2',
    title: 'TOP 1 IN MY HEART',
    type: 'image',
    thumbnail: 'Featured/slide2.jpg',
    mediaUrl: 'Featured/slide2.jpg',
    category: 'Featured',
    tags: ['featured', 'slide', 'second'],
    favorite: true,
    date: '2026-07-30',
    description: 'Trending worldwide. No other show even comes close.',
  },
  {
    id: 'featured-3',
    title: 'AWARD-WINNING LOOKS',
    type: 'image',
    thumbnail: 'Featured/slide3.jpg',
    mediaUrl: 'Featured/slide3.jpg',
    category: 'Featured',
    tags: ['featured', 'slide', 'third'],
    favorite: true,
    date: '2026-07-29',
    description: "Winner of the 'Prettiest Human Alive' award for 365 consecutive days.",
  },
  {
    id: 'featured-4',
    title: 'BREATHTAKING VISUALS',
    type: 'image',
    thumbnail: 'Featured/slide4.jpg',
    mediaUrl: 'Featured/slide4.jpg',
    category: 'Featured',
    tags: ['featured', 'slide', 'fourth'],
    favorite: true,
    date: '2026-07-28',
    description: 'Warning: Viewing may cause sudden loss of words and accelerated heartbeat.',
  },
  {
    id: 'featured-5',
    title: 'WORTH THE BINGE',
    type: 'image',
    thumbnail: 'Featured/slide5.jpg',
    mediaUrl: 'Featured/slide5.jpg',
    category: 'Featured',
    tags: ['featured', 'slide', 'fifth'],
    favorite: true,
    date: '2026-07-27',
    description: "I could look at this face all day and never click 'Skip Intro'.",
  },
  {
    id: 'featured-6',
    title: 'TO BE CONTINUED...',
    type: 'image',
    thumbnail: 'Featured/slide6.jpg',
    mediaUrl: 'Featured/slide6.jpg',
    category: 'Featured',
    tags: ['featured', 'slide', 'sixth'],
    favorite: true,
    date: '2026-07-26',
    description: 'The story of the girl who owns my entire heart. I love you.',
  },
  {
    id: 'her-0',
    title: 'HER Moment #1',
    type: 'video',
    thumbnail: 'Her/Y.jpg',
    mediaUrl: 'Her/C.mp4',
    category: 'HER',
    tags: ["her","love","moments","video"],
    favorite: true,
    date: '2026-07-01',
  },
  {
    id: 'her-1',
    title: 'HER Moment #2',
    type: 'image',
    thumbnail: 'Her/files (1).jpg',
    mediaUrl: 'Her/files (1).jpg',
    category: 'HER',
    tags: ["her","love","moments","image"],
    favorite: true,
    date: '2026-07-02',
  },
  {
    id: 'her-2',
    title: 'HER Moment #3',
    type: 'image',
    thumbnail: 'Her/files (10).jpg',
    mediaUrl: 'Her/files (10).jpg',
    category: 'HER',
    tags: ["her","love","moments","image"],
    favorite: true,
    date: '2026-07-03',
  },
  {
    id: 'her-3',
    title: 'HER Moment #4',
    type: 'image',
    thumbnail: 'Her/files (11).jpg',
    mediaUrl: 'Her/files (11).jpg',
    category: 'HER',
    tags: ["her","love","moments","image"],
    favorite: true,
    date: '2026-07-04',
  },
  {
    id: 'her-4',
    title: 'HER Moment #5',
    type: 'image',
    thumbnail: 'Her/files (14).jpg',
    mediaUrl: 'Her/files (14).jpg',
    category: 'HER',
    tags: ["her","love","moments","image"],
    favorite: true,
    date: '2026-07-05',
  },
  {
    id: 'her-5',
    title: 'HER Moment #6',
    type: 'image',
    thumbnail: 'Her/files (15).jpg',
    mediaUrl: 'Her/files (15).jpg',
    category: 'HER',
    tags: ["her","love","moments","image"],
    favorite: true,
    date: '2026-07-06',
  },
  {
    id: 'her-6',
    title: 'HER Moment #7',
    type: 'image',
    thumbnail: 'Her/files (16).jpg',
    mediaUrl: 'Her/files (16).jpg',
    category: 'HER',
    tags: ["her","love","moments","image"],
    favorite: true,
    date: '2026-07-07',
  },
  {
    id: 'her-7',
    title: 'HER Moment #8',
    type: 'image',
    thumbnail: 'Her/files (2).jpg',
    mediaUrl: 'Her/files (2).jpg',
    category: 'HER',
    tags: ["her","love","moments","image"],
    favorite: true,
    date: '2026-07-08',
  },

  {
    id: 'her-9',
    title: 'HER Moment #10',
    type: 'image',
    thumbnail: 'Her/files (3).jpg',
    mediaUrl: 'Her/files (3).jpg',
    category: 'HER',
    tags: ["her","love","moments","image"],
    favorite: true,
    date: '2026-07-10',
  },

  {
    id: 'her-11',
    title: 'HER Moment #12',
    type: 'image',
    thumbnail: 'Her/files (4).jpg',
    mediaUrl: 'Her/files (4).jpg',
    category: 'HER',
    tags: ["her","love","moments","image"],
    favorite: true,
    date: '2026-07-12',
  },
  {
    id: 'her-12',
    title: 'HER Moment #13',
    type: 'image',
    thumbnail: 'Her/files (6).jpg',
    mediaUrl: 'Her/files (6).jpg',
    category: 'HER',
    tags: ["her","love","moments","image"],
    favorite: true,
    date: '2026-07-13',
  },
  {
    id: 'her-13',
    title: 'HER Moment #14',
    type: 'image',
    thumbnail: 'Her/files (7).jpg',
    mediaUrl: 'Her/files (7).jpg',
    category: 'HER',
    tags: ["her","love","moments","image"],
    favorite: true,
    date: '2026-07-14',
  },
  {
    id: 'her-14',
    title: 'HER Moment #15',
    type: 'image',
    thumbnail: 'Her/files (8).jpg',
    mediaUrl: 'Her/files (8).jpg',
    category: 'HER',
    tags: ["her","love","moments","image"],
    favorite: true,
    date: '2026-07-15',
  },
  {
    id: 'her-15',
    title: 'HER Moment #16',
    type: 'image',
    thumbnail: 'Her/files (9).jpg',
    mediaUrl: 'Her/files (9).jpg',
    category: 'HER',
    tags: ["her","love","moments","image"],
    favorite: true,
    date: '2026-07-16',
  },
  {
    id: 'her-16',
    title: 'HER Moment #17',
    type: 'image',
    thumbnail: 'Her/files.jpg',
    mediaUrl: 'Her/files.jpg',
    category: 'HER',
    tags: ["her","love","moments","image"],
    favorite: true,
    date: '2026-07-17',
  },

  {
    id: 'peeps-0',
    title: 'Peeps Moment #1',
    type: 'image',
    thumbnail: 'Peeps/files (1).jpg',
    mediaUrl: 'Peeps/files (1).jpg',
    category: 'Peeps',
    tags: ["peeps","friends","moments","image"],
    favorite: true,
    date: '2026-06-01',
  },
  {
    id: 'peeps-1',
    title: 'Peeps Moment #2',
    type: 'image',
    thumbnail: 'Peeps/files (12).jpg',
    mediaUrl: 'Peeps/files (12).jpg',
    category: 'Peeps',
    tags: ["peeps","friends","moments","image"],
    favorite: true,
    date: '2026-06-02',
  },
  {
    id: 'peeps-2',
    title: 'Peeps Moment #3',
    type: 'image',
    thumbnail: 'Peeps/files (13).jpg',
    mediaUrl: 'Peeps/files (13).jpg',
    category: 'Peeps',
    tags: ["peeps","friends","moments","image"],
    favorite: true,
    date: '2026-06-03',
  },
  {
    id: 'peeps-3',
    title: 'Peeps Moment #4',
    type: 'image',
    thumbnail: 'Peeps/files (2).jpg',
    mediaUrl: 'Peeps/files (2).jpg',
    category: 'Peeps',
    tags: ["peeps","friends","moments","image"],
    favorite: true,
    date: '2026-06-04',
  },
  {
    id: 'peeps-4',
    title: 'Peeps Moment #5',
    type: 'image',
    thumbnail: 'Peeps/files (3).jpg',
    mediaUrl: 'Peeps/files (3).jpg',
    category: 'Peeps',
    tags: ["peeps","friends","moments","image"],
    favorite: true,
    date: '2026-06-05',
  },
  {
    id: 'peeps-5',
    title: 'Peeps Moment #6',
    type: 'image',
    thumbnail: 'Peeps/files (5).jpg',
    mediaUrl: 'Peeps/files (5).jpg',
    category: 'Peeps',
    tags: ["peeps","friends","moments","image"],
    favorite: true,
    date: '2026-06-06',
  },
  {
    id: 'peeps-6',
    title: 'Peeps Moment #7',
    type: 'image',
    thumbnail: 'Peeps/files.png',
    mediaUrl: 'Peeps/files.png',
    category: 'Peeps',
    tags: ["peeps","friends","moments","image"],
    favorite: true,
    date: '2026-06-07',
  },
]

export function getFavorites() {
  return MEDIA.filter((m) => m.favorite)
}

export function getByCategory(category: string) {
  return MEDIA.filter((m) => m.category === category)
}

export function getByType(type: 'image' | 'video') {
  return MEDIA.filter((m) => m.type === type)
}

export function getRecent() {
  return [...MEDIA].sort(
    (a, b) => new Date(b.date).getTime() - new Date(a.date).getTime(),
  )
}
